#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = PhotoSync
APP_NAME = PhotoSync
PhotoSync_APPLICATION_ICON = 
GNUSTEP_INSTALLATION_DIR = $(HOME)/GNUstep


#
# Resource files
#
PhotoSync_RESOURCE_FILES = \
Resources/PhotoSyncGS.gorm\
Resources/Info-gnustep.plist \
Resources/index.html \
Resources/month.html \
Resources/page.html \
Resources/search.html \
Resources/searchfun.txt \
Resources/style.css \
Resources/year.html

#
# Header files
#
PhotoSync_HEADER_FILES = \
AppController.h \
Controller.h \
Location.h \
Locations.h \
LocEditController.h \
PageWriter.h \
Photo.h \
PhotoClient.h \
SyncSubTask.h \
SyncTask.h

#
# Class files
#
PhotoSync_OBJC_FILES = \
AppController.m \
Controller.m \
Location.m \
Locations.m \
LocEditController.m \
PageWriter.m \
Photo.m \
PhotoClient.m \
SyncSubTask.m \
SyncTask.m

#
# C files
#
PhotoSync_C_FILES = 

PhotoSync_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
